baseURL = "http://example.org/"     # URL of the website
languageCode = "en-us"              # Locale
title = "Acme Corporation"          # Name of the website
theme = "github.com/hugoinaction/Eclectic"      # Name of the theme
# theme = "github.com/hugoinaction/Universal"      # Name of the theme
enableEmoji = true

# sets line numbers in code blocks to on in ``` code fences
[markup.highlight]
    lineNos = true

# enables inline html to render
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[menu]                                                # Menu placement

    [[menu.main]]                                       # Name of the menu
        identifier = "about"                            # Identifier
        name = "About"                                  # Display name (theme specific key)
        url = "/about"                                  # Target URL
        weight = 1.0                                    # Sorting order

    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
        weight = 2.0

    [[menu.main]]
        identifier = "terms"
        name = "Terms"
        url = "/terms"
        weight = 3.0

    [[menu.main]]
        identifier = "privacy"
        name = "Privacy"
        url = "/privacy"
        weight = 4.0

    [[menu.main]]
        identifier = "carousel"
        name = "Carousel"
        url = "/data-driven"
        weight = 5.0

    [[menu.main]]
        identifier = "possibilities"
        name = "Possibilities"
        url = "/example"
        weight = 6.0
        