[[main]]                                      #    - Name of the menu
    identifier = "about"                       #       - Identifier
    name = "About"                             #       - Display name (theme specific key)
    url = "/about"                             #       - Target URL
    weight = 1                               #       - Sorting order

[[main]]   
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 2

[[main]]
    identifier = "carousel"
    name = "Carousel"
    url = "/data-driven"
    weight = 15

[[main]]
    identifier = "possibilites"
    name = "Possibilities"
    url = "/example"
    weight = 16